

name: fue_style
version: 0.0.1
author: muhwa <spx@naver.com>
description: fue style
homepage: https://github.com/naeil/fue-style

environment:
  sdk: '>=2.0.0-dev.17.0 <2.0.0'

dependencies:
  args: '>=0.12.1 <2.0.0'
  logging: '>=0.9.0 <0.12.0'
  path: '>=0.9.0 <2.0.0'
  source_span: '>=1.4.0 <2.0.0'
  collection: '^1.14.6'

dev_dependencies:
  test: ^1.2.0